name: Laravel with React-Inertia deploy

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to Cloud Server
    runs-on: ubuntu-22.04
    env:
        DB_CONNECTION: mysql
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'


    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, bcmath, intl, pdo_mysql, xml

    - name: Install PHP dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader  
      # Sole ejecutar primera vez

    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        DB_CONNECTION: ${{ env.DB_CONNECTION }}
        DB_HOST: ${{ env.DB_HOST }}
        DB_PORT: ${{ env.DB_PORT }}
        DB_DATABASE: ${{ env.DB_DATABASE }}
        DB_USERNAME: ${{ env.DB_USERNAME }}
        DB_PASSWORD: ${{ env.DB_PASSWORD }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        envs: DB_CONNECTION,DB_HOST,DB_PORT,DB_DATABASE,DB_USERNAME,DB_PASSWORD
        script: |
          cd /var/www/eosoftweb
          git pull origin main
          composer install --no-dev --prefer-dist --no-scripts --no-progress --no-suggest --optimize-autoloader
          php artisan migrate --force --no-interaction
          npm ci && npm run build
          chmod -R 755 storage bootstrap/cache
          php artisan cache:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          service nginx restart

    # No excluí porque no puedo correr npm en mi hosting: **/node_modules/**

    #Para correr varios comandos usar run: | comando1 comando2 comando3...

    