name: Laravel with React-Inertia deploy

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to Cloud Server
    runs-on: ubuntu-22.04
    env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        FTP_DESTINATION: ${{ secrets.REMOTE_PATH }}
        DB_CONNECTION: mysql
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

      # Sole ejecutar primera vez
    - name: Install Composer dependencies
      run: composer install --no-dev --prefer-dist --no-scripts --no-progress --no-suggest

    - name: Set Directory Permissions
      run: chmod -R 755 storage bootstrap/cache
        
    #hasta aquí

    - name: Deploy 
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        server-dir: ${{ secrets.REMOTE_PATH }}
        protocol: ftps
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          
    # No excluí porque no puedo correr npm en mi hosting: **/node_modules/**

    #Para correr varios comandos usar run: | comando1 comando2 comando3...

    - name: Post-deployment commands
      uses: appleboy/ssh-action@master
      env:
        DB_CONNECTION: ${{ env.DB_CONNECTION }}
        DB_HOST: ${{ env.DB_HOST }}
        DB_PORT: ${{ env.DB_PORT }}
        DB_DATABASE: ${{ env.DB_DATABASE }}
        DB_USERNAME: ${{ env.DB_USERNAME }}
        DB_PASSWORD: ${{ env.DB_PASSWORD }}
      with:
        host: ${{ secrets.CPANEL_HOST }}
        username: ${{ secrets.CPANEL_USERNAME }}
        password: ${{ secrets.CPANEL_PASSWORD }}
        port: 22
        envs: DB_CONNECTION,DB_HOST,DB_PORT,DB_DATABASE,DB_USERNAME,DB_PASSWORD
        script: |
          cd /var/www/eosoftweb
          sudo php artisan migrate --force --no-interaction
          sudo npm ci
          sudo npm run build
          sudo php artisan config:cache
          sudo php artisan route:cache
          sudo php artisan view:cache
          sudo service nginx restart