name: Laravel with React-Inertia deploy

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to Cloud Server
    runs-on: ubuntu-22.04
    env:
        DB_CONNECTION: mysql
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      # Sole ejecutar primera vez

    - name: Deploy #Full Deploy
      uses: appleboy/ssh-action@master
      env:
        DB_CONNECTION: ${{ env.DB_CONNECTION }}
        DB_HOST: ${{ env.DB_HOST }}
        DB_PORT: ${{ env.DB_PORT }}
        DB_DATABASE: ${{ env.DB_DATABASE }}
        DB_USERNAME: ${{ env.DB_USERNAME }}
        DB_PASSWORD: ${{ env.DB_PASSWORD }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        envs: DB_CONNECTION,DB_HOST,DB_PORT,DB_DATABASE,DB_USERNAME,DB_PASSWORD
        script: |
          cd /var/www/eosoftweb
          git pull origin main
          composer install -n --no-dev --prefer-dist --optimize-autoloader
          php artisan migrate --force --no-interaction
          npm install --production
          npm run build
          php artisan cache:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          service nginx restart
